export const API_USER = "API_USER";
export const API_LOGOUT = "API_LOGOUT";

export const API_TODO = "API_TODO";
export const API_TODOADD = "API_TODOADD";
export const API_TODOUPDATE = "API_TODOUPDATE";
export const API_TODODELETE = "API_TODODELETE";

export const API_CATEGORIE = "API_CATEGORIE";
export const API_ADDCATEGORIE = "API_ADDCATEGORIE";
export const API_EDIT_CATEGORY = "API_EDIT_CATEGORY";
export const API_DELETE_CATEGORY = "API_DELETE_CATEGORY";

export const API_TASK = "API_TASK";
export const API_CHECKTASKINCATE = "API_CHECKTASKINCATE";
export const API_ADDTASKCATE = "API_ADDTASKCATE";
export const API_DELETE_CATEGORYTASK = "API_DELETE_CATEGORYTASK";
export const API_UPDATETASKCATEGORY = "API_UPDATETASKCATEGORY";
export const API_ACHIVETASKCATEGORY = "API_ACHIVETASKCATEGORY";
